/*
  TIER 1 ACADEMY — Session Plans (Section E)
  44 detailed session plans organized by level and sub-band.
  Each plan includes full block structure, coaching emphasis,
  standards, common mistakes, and match play transfer.
*/

import type { PathwayStageId } from './data';

export interface SessionPlanBlock {
  label: string;
  content: string;
}

export interface SessionPlan {
  id: string;
  planNumber: number;
  name: string;
  levelTag: string;
  level: PathwayStageId;
  subBand?: string;
  totalTime: number; // minutes
  objective: string;
  blocks: SessionPlanBlock[];
  coachingEmphasis: string;
  standards: string[];
  commonMistakes: string[];
  matchPlayTransfer: string;
}

export const sessionPlans: SessionPlan[] = [
  // ═══════════════════════════════════════════════════════════════════
  // PREP ORANGE ADVANCED (Plans 1-4)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-1',
    planNumber: 1,
    name: 'Prep Orange Shape and Movement',
    levelTag: 'Prep Orange Advanced',
    level: 'prep',
    subBand: 'Orange Advanced',
    totalTime: 90,
    objective: 'Build shape, spacing, and simple point structure',
    blocks: [
      { label: 'Warm Up', content: 'Skipping, hops, throw catch, jump rope, mini rally' },
      { label: 'Movement', content: 'Three way movement, recovery line drill' },
      { label: 'Main Drill 1', content: 'Forehand Shape Ladder' },
      { label: 'Main Drill 2', content: 'Backhand Contact Box' },
      { label: 'Serve & Return', content: 'Toss Freeze to Target and simple return ready position' },
      { label: 'Point Play', content: 'Two Ball Start Points' },
      { label: 'Competitive Finish', content: 'Crosscourt Rally Race' },
      { label: 'Reflection', content: 'One thing done well, one thing to improve' },
    ],
    coachingEmphasis: 'Spacing before power',
    standards: ['Split step', 'Recovery', 'Shape', 'Focus'],
    commonMistakes: ['Too much speed', 'Not enough correction', 'Random points'],
    matchPlayTransfer: 'Helps players rally and start points with more control',
  },
  {
    id: 'sp-2',
    planNumber: 2,
    name: 'Prep Orange Direction Basics',
    levelTag: 'Prep Orange Advanced',
    level: 'prep',
    subBand: 'Orange Advanced',
    totalTime: 90,
    objective: 'Improve directional control and simple transition awareness',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up and short court topspin' },
      { label: 'Movement', content: 'Mini X drill and figure 8 feet' },
      { label: 'Main Drill 1', content: 'Crosscourt Rally Race' },
      { label: 'Main Drill 2', content: 'Change Direction on Command' },
      { label: 'Serve & Return', content: 'Serve to wide and T boxes, step in return basics' },
      { label: 'Point Play', content: 'Baseline only points' },
      { label: 'Competitive Finish', content: 'Target relay' },
      { label: 'Reflection', content: 'Group circle' },
    ],
    coachingEmphasis: 'Crosscourt first, line only when earned',
    standards: ['Feet active', 'No reaching', 'No random line changes'],
    commonMistakes: ['Overcoaching details at expense of reps'],
    matchPlayTransfer: 'Stronger directional discipline in points',
  },
  {
    id: 'sp-3',
    planNumber: 3,
    name: 'Prep Orange Extended Foundation',
    levelTag: 'Prep Orange Advanced',
    level: 'prep',
    subBand: 'Orange Advanced',
    totalTime: 120,
    objective: 'Develop a complete 2 hour foundation session',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up and short court topspin' },
      { label: 'Movement', content: 'Three way movement and recovery line rebuild' },
      { label: 'Main Drill 1', content: 'Forehand Shape Ladder' },
      { label: 'Main Drill 2', content: 'Backhand Contact Window' },
      { label: 'Serve & Return', content: 'Toss Window Fix and Step In Return Start' },
      { label: 'Point Play', content: 'Two Ball Start Points and Crosscourt only game' },
      { label: 'Competitive Finish', content: 'Partner Call and Cover doubles intro' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'Quality reps over rushed complexity',
    standards: ['Balance', 'Shape', 'Recovery', 'Communication'],
    commonMistakes: ['Too much standing', 'Not enough movement accountability'],
    matchPlayTransfer: 'Gives players a more complete early competitive base',
  },
  {
    id: 'sp-4',
    planNumber: 4,
    name: 'Prep Orange Competitive Basics',
    levelTag: 'Prep Orange Advanced',
    level: 'prep',
    subBand: 'Orange Advanced',
    totalTime: 120,
    objective: 'Introduce structured competition without losing fundamentals',
    blocks: [
      { label: 'Warm Up', content: 'Coordination warm up and short court control' },
      { label: 'Movement', content: 'Mini X and short ball move forward' },
      { label: 'Main Drill 1', content: 'Change Direction on Command' },
      { label: 'Main Drill 2', content: 'Approach and First Volley Basics' },
      { label: 'Serve & Return', content: 'Toss Freeze to Target and return ready shape' },
      { label: 'Point Play', content: 'Neutral Start Six Ball Points' },
      { label: 'Competitive Finish', content: 'No Free First Four game simplified' },
      { label: 'Reflection', content: 'Player shares one smart decision' },
    ],
    coachingEmphasis: 'Structure inside competition',
    standards: ['Discipline before creativity'],
    commonMistakes: ['Too much open play too early'],
    matchPlayTransfer: 'Prepares players for more structured point play',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PREP GREEN ADVANCED (Plans 5-8)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-5',
    planNumber: 5,
    name: 'Prep Green Full Court Bridge',
    levelTag: 'Prep Green Advanced',
    level: 'prep',
    subBand: 'Green Advanced',
    totalTime: 90,
    objective: 'Bridge green ball players toward full court habits',
    blocks: [
      { label: 'Warm Up', content: 'Athletic literacy warm up' },
      { label: 'Movement', content: 'Three way movement feed' },
      { label: 'Main Drill 1', content: 'Forehand Shape Ladder' },
      { label: 'Main Drill 2', content: 'Change Direction on Command' },
      { label: 'Serve & Return', content: 'Toss Freeze to Target and Step In Return Start' },
      { label: 'Point Play', content: 'Two Ball Start Points' },
      { label: 'Competitive Finish', content: 'Crosscourt Rally Race' },
      { label: 'Reflection', content: 'Quick written note' },
    ],
    coachingEmphasis: 'Full court habits without rushing',
    standards: ['Spacing', 'Shape', 'Recovery'],
    commonMistakes: ['Flattening too early'],
    matchPlayTransfer: 'Prepares players for yellow ball direction and control',
  },
  {
    id: 'sp-6',
    planNumber: 6,
    name: 'Prep Green Transition Start',
    levelTag: 'Prep Green Advanced',
    level: 'prep',
    subBand: 'Green Advanced',
    totalTime: 90,
    objective: 'Improve short ball recognition and first transition forward',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and mini volley touch' },
      { label: 'Movement', content: 'Short ball footwork ladder' },
      { label: 'Main Drill 1', content: 'Approach and First Volley Basics' },
      { label: 'Main Drill 2', content: 'Backhand Contact Box' },
      { label: 'Serve & Return', content: 'Step in return and serve target basics' },
      { label: 'Point Play', content: 'Attackable ball go live simplified' },
      { label: 'Competitive Finish', content: 'Transition wins double' },
      { label: 'Reflection', content: 'Circle reset' },
    ],
    coachingEmphasis: 'Move forward with balance',
    standards: ['Correct ball selection', 'Split before volley'],
    commonMistakes: ['Charging without purpose'],
    matchPlayTransfer: 'Teaches first layer of offensive transition',
  },
  {
    id: 'sp-7',
    planNumber: 7,
    name: 'Prep Green Extended Rally Day',
    levelTag: 'Prep Green Advanced',
    level: 'prep',
    subBand: 'Green Advanced',
    totalTime: 120,
    objective: 'Build rally stability and directional confidence',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up and short court rally' },
      { label: 'Movement', content: 'Figure 8 feet and recovery line' },
      { label: 'Main Drill 1', content: 'Crosscourt Rally Race' },
      { label: 'Main Drill 2', content: 'Change Direction on Command' },
      { label: 'Serve & Return', content: 'Toss Window Fix and Return Timing Window' },
      { label: 'Point Play', content: 'Neutral Start Six Ball Points' },
      { label: 'Competitive Finish', content: 'Direction locked crosscourt game' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'Patience and balance',
    standards: ['Margin', 'Split', 'Recovery'],
    commonMistakes: ['Overhitting during rally drills'],
    matchPlayTransfer: 'More stable neutral tennis',
  },
  {
    id: 'sp-8',
    planNumber: 8,
    name: 'Prep Green Match Basics',
    levelTag: 'Prep Green Advanced',
    level: 'prep',
    subBand: 'Green Advanced',
    totalTime: 120,
    objective: 'Expose players to real point logic and score awareness',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and short court shape' },
      { label: 'Movement', content: 'Three way movement and recover line rebuild' },
      { label: 'Main Drill 1', content: 'Approach and First Volley Basics' },
      { label: 'Main Drill 2', content: 'Serve Recover Split' },
      { label: 'Serve & Return', content: 'Deuce Side Return Drive simplified' },
      { label: 'Point Play', content: 'Two Ball Start Points and baseline only game' },
      { label: 'Competitive Finish', content: 'First to 4 short set' },
      { label: 'Reflection', content: 'One point learned from pressure' },
    ],
    coachingEmphasis: 'Point building over random winners',
    standards: ['Score clarity', 'First recovery', 'Discipline'],
    commonMistakes: ['Score confusion and emotional drops'],
    matchPlayTransfer: 'Prepares players for more realistic competition',
  },

  // ═══════════════════════════════════════════════════════════════════
  // JASA UTR 1-2 (Plans 9-12)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-9',
    planNumber: 9,
    name: 'JASA Full Court Foundation',
    levelTag: 'JASA UTR 1 to 2',
    level: 'jasa',
    subBand: 'UTR 1-2',
    totalTime: 90,
    objective: 'Establish full court depth and directional discipline',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and mini rally shape' },
      { label: 'Movement', content: 'Recover line rebuild and defend reset footwork' },
      { label: 'Main Drill 1', content: 'Full Court Crosscourt Discipline' },
      { label: 'Main Drill 2', content: 'Deep Middle to Open Court' },
      { label: 'Serve & Return', content: 'Return Deep Middle Lock and Second Serve Shape Channel' },
      { label: 'Point Play', content: 'Neutral Start Six Ball Points' },
      { label: 'Competitive Finish', content: 'Emotional discipline game' },
      { label: 'Reflection', content: 'Quick coach recap' },
    ],
    coachingEmphasis: 'Full court patience',
    standards: ['Depth', 'Recovery', 'Calm body language'],
    commonMistakes: ['Trying to play too advanced too soon'],
    matchPlayTransfer: 'Gives players real yellow ball base',
  },
  {
    id: 'sp-10',
    planNumber: 10,
    name: 'JASA Attack Decision Day',
    levelTag: 'JASA UTR 1 to 2',
    level: 'jasa',
    subBand: 'UTR 1-2',
    totalTime: 90,
    objective: 'Improve short ball recognition and point timing',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Short ball movement and split step timing' },
      { label: 'Main Drill 1', content: 'Attackable Ball Recognition' },
      { label: 'Main Drill 2', content: 'Defend and Reset' },
      { label: 'Serve & Return', content: 'Toss Window Fix and Return Timing Window' },
      { label: 'Point Play', content: 'Attackable Ball Go Live' },
      { label: 'Competitive Finish', content: 'Transition wins double' },
      { label: 'Reflection', content: 'One good decision shared' },
    ],
    coachingEmphasis: 'Choose the right ball',
    standards: ['No forcing neutral balls'],
    commonMistakes: ['Overattacking'],
    matchPlayTransfer: 'Better offensive timing',
  },
  {
    id: 'sp-11',
    planNumber: 11,
    name: 'JASA Extended Structure',
    levelTag: 'JASA UTR 1 to 2',
    level: 'jasa',
    subBand: 'UTR 1-2',
    totalTime: 120,
    objective: 'Create a complete yellow ball development session',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up and short court control' },
      { label: 'Movement', content: 'Three way movement and defensive reset patterns' },
      { label: 'Main Drill 1', content: 'Full Court Crosscourt Discipline' },
      { label: 'Main Drill 2', content: 'Forehand Dictation Feed' },
      { label: 'Serve & Return', content: 'Wide Body T Serve Ladder and Return Deep Middle Lock' },
      { label: 'Point Play', content: 'Deep Middle to Open Court live and Neutral Start Six Ball Points' },
      { label: 'Competitive Finish', content: 'JASA Tiebreak Pressure Block' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'Structure and consistency',
    standards: ['Footwork', 'Depth', 'Emotional stability'],
    commonMistakes: ['Too much open play'],
    matchPlayTransfer: 'Stronger full court habits',
  },
  {
    id: 'sp-12',
    planNumber: 12,
    name: 'JASA Competitive Foundations',
    levelTag: 'JASA UTR 1 to 2',
    level: 'jasa',
    subBand: 'UTR 1-2',
    totalTime: 120,
    objective: 'Blend structure with scoring pressure',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Recover line drill and split timing' },
      { label: 'Main Drill 1', content: 'Deep Middle to Open Court' },
      { label: 'Main Drill 2', content: 'Compact Return Channel' },
      { label: 'Serve & Return', content: 'Three Spot Serve Circuit simplified' },
      { label: 'Point Play', content: 'Attackable Ball Go Live and Deuce Game Pressure simplified' },
      { label: 'Competitive Finish', content: 'Partner Call and Cover doubles' },
      { label: 'Reflection', content: 'Player note on pressure' },
    ],
    coachingEmphasis: 'Score with discipline',
    standards: ['Clear decisions', 'Score awareness'],
    commonMistakes: ['Rushing under score'],
    matchPlayTransfer: 'Better pressure behavior',
  },

  // ═══════════════════════════════════════════════════════════════════
  // JASA UTR 2-3 (Plans 13-16)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-13',
    planNumber: 13,
    name: 'JASA Pattern Build',
    levelTag: 'JASA UTR 2 to 3',
    level: 'jasa',
    subBand: 'UTR 2-3',
    totalTime: 90,
    objective: 'Build first clear rally patterns',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and short court shape' },
      { label: 'Movement', content: 'Recover line and forehand run around movement' },
      { label: 'Main Drill 1', content: 'Forehand Dictation Feed' },
      { label: 'Main Drill 2', content: 'Deep Middle to Open Court' },
      { label: 'Serve & Return', content: 'Serve Plus One Open Court and Compact Return Channel' },
      { label: 'Point Play', content: 'Tactical Pattern Points' },
      { label: 'Competitive Finish', content: 'Deuce Game Pressure' },
      { label: 'Reflection', content: 'Quick tactical recap' },
    ],
    coachingEmphasis: 'Simple patterns repeated well',
    standards: ['Discipline', 'Spacing', 'Recovery'],
    commonMistakes: ['Overcomplicating patterns'],
    matchPlayTransfer: 'More usable patterns in competition',
  },
  {
    id: 'sp-14',
    planNumber: 14,
    name: 'JASA Transition and First Strike',
    levelTag: 'JASA UTR 2 to 3',
    level: 'jasa',
    subBand: 'UTR 2-3',
    totalTime: 90,
    objective: 'Connect short ball recognition to point finishing',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Short ball move forward and split' },
      { label: 'Main Drill 1', content: 'Attackable Ball Recognition' },
      { label: 'Main Drill 2', content: 'Transition Footwork Ladder' },
      { label: 'Serve & Return', content: 'Wide Body T Serve Ladder and Return Plus One Neutralize and Go' },
      { label: 'Point Play', content: 'Transition Wins Double' },
      { label: 'Competitive Finish', content: 'Emotional discipline game' },
      { label: 'Reflection', content: 'One pattern to trust' },
    ],
    coachingEmphasis: 'Earn offense',
    standards: ['Correct ball selection', 'First recovery'],
    commonMistakes: ['Attacking too early'],
    matchPlayTransfer: 'Better transition decisions',
  },
  {
    id: 'sp-15',
    planNumber: 15,
    name: 'JASA Two Hour Match Builder',
    levelTag: 'JASA UTR 2 to 3',
    level: 'jasa',
    subBand: 'UTR 2-3',
    totalTime: 120,
    objective: 'Develop a more complete match relevant session',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and short court topspin' },
      { label: 'Movement', content: 'Defend reset and recover line' },
      { label: 'Main Drill 1', content: 'Forehand Dictation Feed' },
      { label: 'Main Drill 2', content: 'Defend and Reset' },
      { label: 'Serve & Return', content: 'Serve Plus One Open Court and Return Deep Middle Lock' },
      { label: 'Point Play', content: 'Return Plus One Score and Attackable Ball Go Live' },
      { label: 'Competitive Finish', content: 'Short Set Sprint' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'Pattern plus recovery',
    standards: ['Shape', 'Footwork', 'Emotional steadiness'],
    commonMistakes: ['Random plus one choices'],
    matchPlayTransfer: 'Sharper point starts and recovery',
  },
  {
    id: 'sp-16',
    planNumber: 16,
    name: 'JASA Pressure Prep',
    levelTag: 'JASA UTR 2 to 3',
    level: 'jasa',
    subBand: 'UTR 2-3',
    totalTime: 120,
    objective: 'Prepare players for more match pressure',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Transition movement and defensive recovery' },
      { label: 'Main Drill 1', content: 'Compact Return Channel' },
      { label: 'Main Drill 2', content: 'Wide Body T Serve Ladder' },
      { label: 'Serve & Return', content: 'Return Routine Reset and Second Serve Shape Channel' },
      { label: 'Point Play', content: 'JASA Tiebreak Pressure Block and Neutral Start Six Ball Points' },
      { label: 'Competitive Finish', content: 'Comeback From 0-3 simplified' },
      { label: 'Reflection', content: 'Note on pressure response' },
    ],
    coachingEmphasis: 'Routines and calm decisions',
    standards: ['Body language', 'Score awareness'],
    commonMistakes: ['Emotional overreaction'],
    matchPlayTransfer: 'Better pressure readiness',
  },

  // ═══════════════════════════════════════════════════════════════════
  // ASA UTR 3-5 (Plans 17-20)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-17',
    planNumber: 17,
    name: 'ASA 3-5 First Strike Basics',
    levelTag: 'ASA UTR 3 to 5',
    level: 'asa',
    subBand: 'UTR 3-5',
    totalTime: 90,
    objective: 'Establish serve plus one and return plus one structure',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Recover line and split timing' },
      { label: 'Main Drill 1', content: 'Two Cross One Line Pattern' },
      { label: 'Main Drill 2', content: 'Backhand Wall Pattern' },
      { label: 'Serve & Return', content: 'Serve Wide Plus Forehand Middle and Return Deep Cross Then Hold Middle' },
      { label: 'Point Play', content: 'Serve Plus One Game to Seven' },
      { label: 'Competitive Finish', content: 'No Free First Four' },
      { label: 'Reflection', content: 'Pattern recap' },
    ],
    coachingEmphasis: 'First four balls matter',
    standards: ['Recovery', 'Shape', 'Simple targets'],
    commonMistakes: ['Trying to finish too early'],
    matchPlayTransfer: 'Stronger point starts',
  },
  {
    id: 'sp-18',
    planNumber: 18,
    name: 'ASA 3-5 Build the Neutral Game',
    levelTag: 'ASA UTR 3 to 5',
    level: 'asa',
    subBand: 'UTR 3-5',
    totalTime: 90,
    objective: 'Improve rally tolerance and point construction',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and mini shape' },
      { label: 'Movement', content: 'Defensive reset movement' },
      { label: 'Main Drill 1', content: 'Backhand Wall Pattern' },
      { label: 'Main Drill 2', content: 'Wide Ball Defensive Reset' },
      { label: 'Serve & Return', content: 'Return Deep Middle Lock and Second Serve Trust Builder' },
      { label: 'Point Play', content: 'Neutral Start Six Ball Points upper version' },
      { label: 'Competitive Finish', content: 'Offense Versus Defense Scoring' },
      { label: 'Reflection', content: 'One neutral pattern to trust' },
    ],
    coachingEmphasis: 'Stay neutral until earned',
    standards: ['Margin', 'Body line', 'Calm resets'],
    commonMistakes: ['Forcing offense under pressure'],
    matchPlayTransfer: 'Better neutral phase in matches',
  },
  {
    id: 'sp-19',
    planNumber: 19,
    name: 'ASA 3-5 Two Hour Competitive Day',
    levelTag: 'ASA UTR 3 to 5',
    level: 'asa',
    subBand: 'UTR 3-5',
    totalTime: 120,
    objective: 'Blend structure and live competition',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Recover line and short ball footwork' },
      { label: 'Main Drill 1', content: 'Short Ball Kill Zone' },
      { label: 'Main Drill 2', content: 'Two Cross One Line Pattern' },
      { label: 'Serve & Return', content: 'First Serve Three Spot Circuit and Return Plus One Score' },
      { label: 'Point Play', content: 'Tactical Pattern Points and Attackable Ball Go Live' },
      { label: 'Competitive Finish', content: 'Short Set Sprint' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'Disciplined offense',
    standards: ['Correct attack ball', 'Plus one logic'],
    commonMistakes: ['Offense without setup'],
    matchPlayTransfer: 'Sharper first strike and attack timing',
  },
  {
    id: 'sp-20',
    planNumber: 20,
    name: 'ASA 3-5 Serve Return Match Builder',
    levelTag: 'ASA UTR 3 to 5',
    level: 'asa',
    subBand: 'UTR 3-5',
    totalTime: 120,
    objective: 'Strengthen point starting quality',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Return footwork and serve recover split' },
      { label: 'Main Drill 1', content: 'Serve Wide Plus Forehand Middle' },
      { label: 'Main Drill 2', content: 'Return Deep Cross Then Hold Middle' },
      { label: 'Serve & Return', content: 'Deuce Wide Ladder and Ad T Command' },
      { label: 'Point Play', content: 'Server Versus Returner Race' },
      { label: 'Competitive Finish', content: 'Break Point Down Scenario' },
      { label: 'Reflection', content: 'One serve and one return goal' },
    ],
    coachingEmphasis: 'Win the start of the point',
    standards: ['Routines', 'Recovery', 'Smart targets'],
    commonMistakes: ['No plan on first two balls'],
    matchPlayTransfer: 'Better service and return games',
  },

  // ═══════════════════════════════════════════════════════════════════
  // ASA UTR 5-7 (Plans 21-24)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-21',
    planNumber: 21,
    name: 'ASA 5-7 Pattern Discipline',
    levelTag: 'ASA UTR 5 to 7',
    level: 'asa',
    subBand: 'UTR 5-7',
    totalTime: 90,
    objective: 'Reinforce rally pattern discipline under speed',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Absorb and recover movement' },
      { label: 'Main Drill 1', content: 'Two Cross One Line Pattern' },
      { label: 'Main Drill 2', content: 'Absorb and Redirect' },
      { label: 'Serve & Return', content: 'Random Target Serve Call and Block Return Under Pace' },
      { label: 'Point Play', content: 'Tactical Pattern Points' },
      { label: 'Competitive Finish', content: 'Deuce Game Pressure' },
      { label: 'Reflection', content: 'Pattern review' },
    ],
    coachingEmphasis: 'Hold shape under pace',
    standards: ['Disciplined line changes', 'Stable body line'],
    commonMistakes: ['Rushing line change'],
    matchPlayTransfer: 'Stronger rally IQ',
  },
  {
    id: 'sp-22',
    planNumber: 22,
    name: 'ASA 5-7 Offense Timing',
    levelTag: 'ASA UTR 5 to 7',
    level: 'asa',
    subBand: 'UTR 5-7',
    totalTime: 90,
    objective: 'Improve attack ball recognition and point finishing',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Short ball move and recovery' },
      { label: 'Main Drill 1', content: 'Short Ball Kill Zone' },
      { label: 'Main Drill 2', content: 'Pace Absorb to Offense' },
      { label: 'Serve & Return', content: 'Second Serve Attack Window and Serve Recover Split' },
      { label: 'Point Play', content: 'Attackable Ball Go Live upper version' },
      { label: 'Competitive Finish', content: 'First Strike Race' },
      { label: 'Reflection', content: 'Best attack decision shared' },
    ],
    coachingEmphasis: 'Offense comes from the right ball',
    standards: ['Balance', 'Target discipline', 'Recovery'],
    commonMistakes: ['Overattacking neutral balls'],
    matchPlayTransfer: 'Smarter and more effective offense',
  },
  {
    id: 'sp-23',
    planNumber: 23,
    name: 'ASA 5-7 Extended Match Prep',
    levelTag: 'ASA UTR 5 to 7',
    level: 'asa',
    subBand: 'UTR 5-7',
    totalTime: 120,
    objective: 'Build tournament relevant pressure habits',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and mini tennis control' },
      { label: 'Movement', content: 'Defensive reset and split timing' },
      { label: 'Main Drill 1', content: 'Absorb and Redirect' },
      { label: 'Main Drill 2', content: 'Short Ball Kill Zone' },
      { label: 'Serve & Return', content: 'Tiebreak First Serve Pressure and Return Depth Channel Game' },
      { label: 'Point Play', content: 'Break Point Down Scenario and Comeback From 0-3' },
      { label: 'Competitive Finish', content: 'Closing Game at 5-4' },
      { label: 'Reflection', content: 'Journal on pressure behavior' },
    ],
    coachingEmphasis: 'Keep identity under pressure',
    standards: ['Routines', 'Emotional control', 'Pattern trust'],
    commonMistakes: ['Panic decision making'],
    matchPlayTransfer: 'Stronger tournament composure',
  },
  {
    id: 'sp-24',
    planNumber: 24,
    name: 'ASA 5-7 Doubles and Singles Blend',
    levelTag: 'ASA UTR 5 to 7',
    level: 'asa',
    subBand: 'UTR 5-7',
    totalTime: 120,
    objective: 'Build singles point structure and doubles team awareness',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Transition feet and reflex hands' },
      { label: 'Main Drill 1', content: 'ASA Doubles First Volley Pattern' },
      { label: 'Main Drill 2', content: 'Middle Ball Ownership' },
      { label: 'Serve & Return', content: 'Serve Spot and Poach Window plus Return Team Lockout' },
      { label: 'Point Play', content: 'Tactical Pattern Points singles' },
      { label: 'Competitive Finish', content: 'Doubles Closing Tiebreak' },
      { label: 'Reflection', content: 'Team communication review' },
    ],
    coachingEmphasis: 'Clear choices and partner awareness',
    standards: ['Communication', 'First volley discipline', 'Smart spacing'],
    commonMistakes: ['Doubles treated like singles'],
    matchPlayTransfer: 'Stronger doubles understanding without losing singles quality',
  },

  // ═══════════════════════════════════════════════════════════════════
  // ASA UTR 7-10 (Plans 25-28)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-25',
    planNumber: 25,
    name: 'ASA 7-10 High Pace Structure',
    levelTag: 'ASA UTR 7 to 10',
    level: 'asa',
    subBand: 'UTR 7-10',
    totalTime: 90,
    objective: 'Hold structure under higher pace',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Pace absorb footwork' },
      { label: 'Main Drill 1', content: 'Absorb and Redirect' },
      { label: 'Main Drill 2', content: 'Short Ball Kill Zone' },
      { label: 'Serve & Return', content: 'Block Return Under Pace and Random Target Serve Call' },
      { label: 'Point Play', content: 'No Free First Four' },
      { label: 'Competitive Finish', content: 'One Changeover Adjustment' },
      { label: 'Reflection', content: 'Tactical adjustment review' },
    ],
    coachingEmphasis: 'Composure at speed',
    standards: ['Body line', 'Recovery', 'Decision quality'],
    commonMistakes: ['Playing fast but sloppy'],
    matchPlayTransfer: 'More stable high pace competition',
  },
  {
    id: 'sp-26',
    planNumber: 26,
    name: 'ASA 7-10 Pressure Identity',
    levelTag: 'ASA UTR 7 to 10',
    level: 'asa',
    subBand: 'UTR 7-10',
    totalTime: 90,
    objective: 'Train pressure routines and first strike identity',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Recover split after serve and return' },
      { label: 'Main Drill 1', content: 'Serve Under Scoreboard Pressure' },
      { label: 'Main Drill 2', content: 'Return Compactness Lock' },
      { label: 'Serve & Return', content: 'Tiebreak First Serve Pressure and Serve Return Tiebreak Starts' },
      { label: 'Point Play', content: 'Break Point Down Scenario' },
      { label: 'Competitive Finish', content: 'Closing Game at 5-4' },
      { label: 'Reflection', content: 'Routine note' },
    ],
    coachingEmphasis: 'Same behavior under pressure',
    standards: ['Routines', 'Smart target choices', 'Emotional calm'],
    commonMistakes: ['Changing identity in pressure'],
    matchPlayTransfer: 'Better clutch serving and returning',
  },
  {
    id: 'sp-27',
    planNumber: 27,
    name: 'ASA 7-10 Two Hour Tournament Day',
    levelTag: 'ASA UTR 7 to 10',
    level: 'asa',
    subBand: 'UTR 7-10',
    totalTime: 120,
    objective: 'Build a tournament style practice block',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Absorb and recover, short ball move' },
      { label: 'Main Drill 1', content: 'Backhand Wall Pattern advanced' },
      { label: 'Main Drill 2', content: 'Short Ball Kill Zone advanced' },
      { label: 'Serve & Return', content: 'First Serve Three Spot Circuit, Return Depth Channel Game' },
      { label: 'Point Play', content: 'Tactical Pattern Points, Offense Versus Defense Scoring' },
      { label: 'Competitive Finish', content: 'Match Rehearsal Four Game Block' },
      { label: 'Reflection', content: 'Journal tactical adjustment' },
    ],
    coachingEmphasis: 'Tournament transfer',
    standards: ['Shape under pace', 'Disciplined attack', 'Routines'],
    commonMistakes: ['No tactical clarity in live sets'],
    matchPlayTransfer: 'Direct match readiness',
  },
  {
    id: 'sp-28',
    planNumber: 28,
    name: 'ASA 7-10 Advanced Doubles Block',
    levelTag: 'ASA UTR 7 to 10',
    level: 'asa',
    subBand: 'UTR 7-10',
    totalTime: 120,
    objective: 'Sharpen high level doubles movement and first strike play',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and reflex hands' },
      { label: 'Movement', content: 'Net move and recovery patterns' },
      { label: 'Main Drill 1', content: 'Serve Spot and Poach Window' },
      { label: 'Main Drill 2', content: 'Fake Poach Freeze' },
      { label: 'Serve & Return', content: 'Return Team Lockout and Server Cover Read' },
      { label: 'Point Play', content: 'Doubles First Volley Pattern live' },
      { label: 'Competitive Finish', content: 'Doubles Closing Tiebreak' },
      { label: 'Reflection', content: 'Team pattern recap' },
    ],
    coachingEmphasis: 'Connected movement and trust',
    standards: ['Communication', 'Poach timing', 'Coverage'],
    commonMistakes: ['Random poaching', 'Poor serve logic'],
    matchPlayTransfer: 'Stronger competitive doubles',
  },

  // ═══════════════════════════════════════════════════════════════════
  // FTA UTR 3-5 (Plans 29-32)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-29',
    planNumber: 29,
    name: 'FTA 3-5 Volume and Structure',
    levelTag: 'FTA UTR 3 to 5',
    level: 'fta',
    subBand: 'UTR 3-5',
    totalTime: 90,
    objective: 'Use extra time and focus to build stronger basics than ASA',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Recovery line and short ball move' },
      { label: 'Main Drill 1', content: 'Backhand Wall Pattern' },
      { label: 'Main Drill 2', content: 'Serve Pattern Rehearsal Block simple' },
      { label: 'Serve & Return', content: 'Deuce Wide Ladder and Return Deep Middle Lock' },
      { label: 'Point Play', content: 'Serve Plus One Game to Seven' },
      { label: 'Competitive Finish', content: 'No Free First Four' },
      { label: 'Reflection', content: 'Coach note on one pattern' },
    ],
    coachingEmphasis: 'More reps, more detail, more accountability',
    standards: ['Quality over speed', 'Clean footwork', 'Pattern ownership'],
    commonMistakes: ['Treating FTA like just longer ASA'],
    matchPlayTransfer: 'Stronger point starts and discipline',
  },
  {
    id: 'sp-30',
    planNumber: 30,
    name: 'FTA 3-5 Transition Builder',
    levelTag: 'FTA UTR 3 to 5',
    level: 'fta',
    subBand: 'UTR 3-5',
    totalTime: 90,
    objective: 'Develop better transition skills and finishing choices',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up and volley touch' },
      { label: 'Movement', content: 'Transition footwork ladder' },
      { label: 'Main Drill 1', content: 'Approach and First Volley Basics advanced' },
      { label: 'Main Drill 2', content: 'Defensive Height Restore' },
      { label: 'Serve & Return', content: 'Serve Recover Split and Return Routine Reset' },
      { label: 'Point Play', content: 'Transition Wins Double' },
      { label: 'Competitive Finish', content: 'Deuce Game Pressure simplified' },
      { label: 'Reflection', content: 'Player note on moving forward' },
    ],
    coachingEmphasis: 'Move through the court with balance',
    standards: ['Correct approach ball', 'First volley discipline'],
    commonMistakes: ['Overcharging net'],
    matchPlayTransfer: 'Better transition play',
  },
  {
    id: 'sp-31',
    planNumber: 31,
    name: 'FTA 3-5 Two Hour Build',
    levelTag: 'FTA UTR 3 to 5',
    level: 'fta',
    subBand: 'UTR 3-5',
    totalTime: 120,
    objective: 'Use extra FTA time for deeper pattern repetition',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Recover line and split patterns' },
      { label: 'Main Drill 1', content: 'Serve Pattern Rehearsal Block' },
      { label: 'Main Drill 2', content: 'Return Plus One Score' },
      { label: 'Serve & Return', content: 'Three Spot Serve Circuit and Return Deep Middle Lock' },
      { label: 'Point Play', content: 'Tactical Pattern Points' },
      { label: 'Competitive Finish', content: 'Short Set Sprint' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'More detailed repetition than afterschool',
    standards: ['Pattern clarity', 'Recovery', 'Emotional calm'],
    commonMistakes: ['Too much random live play'],
    matchPlayTransfer: 'Stronger match plans',
  },
  {
    id: 'sp-32',
    planNumber: 32,
    name: 'FTA 3-5 Pressure Foundations',
    levelTag: 'FTA UTR 3 to 5',
    level: 'fta',
    subBand: 'UTR 3-5',
    totalTime: 120,
    objective: 'Introduce pressure identity with more time and feedback',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Defend and reset movement' },
      { label: 'Main Drill 1', content: 'Second Serve Trust Builder' },
      { label: 'Main Drill 2', content: 'Return Routine Reset' },
      { label: 'Serve & Return', content: 'Tiebreak First Serve Pressure and Return Timing Window' },
      { label: 'Point Play', content: 'Comeback From 0-3 and Break Point Down Scenario' },
      { label: 'Competitive Finish', content: 'Emotional Discipline Game' },
      { label: 'Reflection', content: 'Note on routine under pressure' },
    ],
    coachingEmphasis: 'Routine before result',
    standards: ['Same behavior under score'],
    commonMistakes: ['Making pressure work too emotional'],
    matchPlayTransfer: 'Calmer performance under stress',
  },

  // ═══════════════════════════════════════════════════════════════════
  // FTA UTR 5-8 (Plans 33-36)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-33',
    planNumber: 33,
    name: 'FTA 5-8 Pattern Density',
    levelTag: 'FTA UTR 5 to 8',
    level: 'fta',
    subBand: 'UTR 5-8',
    totalTime: 90,
    objective: 'Build repeatable patterns with more density than ASA',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Absorb and recover movement' },
      { label: 'Main Drill 1', content: 'FTA Serve Plus Two Sequence' },
      { label: 'Main Drill 2', content: 'Pace Absorb to Offense' },
      { label: 'Serve & Return', content: 'Random Target Serve Call and Block Return Under Pace' },
      { label: 'Point Play', content: 'Tactical Pattern Points' },
      { label: 'Competitive Finish', content: 'One Changeover Adjustment' },
      { label: 'Reflection', content: 'Pattern summary' },
    ],
    coachingEmphasis: 'Connect first three balls',
    standards: ['Disciplined patterns', 'Body line', 'Recovery'],
    commonMistakes: ['Overcomplicating before basics are sharp'],
    matchPlayTransfer: 'Stronger first three ball structure',
  },
  {
    id: 'sp-34',
    planNumber: 34,
    name: 'FTA 5-8 Pressure and Recovery',
    levelTag: 'FTA UTR 5 to 8',
    level: 'fta',
    subBand: 'UTR 5-8',
    totalTime: 90,
    objective: 'Improve resilience and transition from defense',
    blocks: [
      { label: 'Warm Up', content: 'Athletic warm up' },
      { label: 'Movement', content: 'Defend reset and transition feet' },
      { label: 'Main Drill 1', content: 'Pace Absorb to Offense' },
      { label: 'Main Drill 2', content: 'FTA Transition Waves' },
      { label: 'Serve & Return', content: 'Serve Under Scoreboard Pressure and Return Depth Channel' },
      { label: 'Point Play', content: 'Defend Then Earn Offense' },
      { label: 'Competitive Finish', content: 'Closing Game at 5-4' },
      { label: 'Reflection', content: 'Note on best pressure behavior' },
    ],
    coachingEmphasis: 'Recover mentally and physically',
    standards: ['Defensive height', 'First recovery', 'Routines'],
    commonMistakes: ['Forcing counter too early'],
    matchPlayTransfer: 'Better pressure response and transition choice',
  },
  {
    id: 'sp-35',
    planNumber: 35,
    name: 'FTA 5-8 Two Hour Tactical Day',
    levelTag: 'FTA UTR 5 to 8',
    level: 'fta',
    subBand: 'UTR 5-8',
    totalTime: 120,
    objective: 'Use full time structure for deeper tactical reps',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Pace absorb footwork and recovery' },
      { label: 'Main Drill 1', content: 'Opponent Type Pattern Block' },
      { label: 'Main Drill 2', content: 'FTA Serve Plus Two Sequence' },
      { label: 'Serve & Return', content: 'Return Lock and Counter simplified, Three Spot Serve Circuit' },
      { label: 'Point Play', content: 'Match Pattern Rebuild and Tactical Pattern Points' },
      { label: 'Competitive Finish', content: 'Match Rehearsal Four Game Block' },
      { label: 'Reflection', content: 'Journaling' },
    ],
    coachingEmphasis: 'Pattern logic over random shot making',
    standards: ['Tactical understanding', 'Recovery spacing', 'Calm decisions'],
    commonMistakes: ['Not explaining why pattern fits opponent'],
    matchPlayTransfer: 'More intelligent match preparation',
  },
  {
    id: 'sp-36',
    planNumber: 36,
    name: 'FTA 5-8 Doubles and Net Day',
    levelTag: 'FTA UTR 5 to 8',
    level: 'fta',
    subBand: 'UTR 5-8',
    totalTime: 120,
    objective: 'Sharpen transition and doubles closing skills',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and reflex hands' },
      { label: 'Movement', content: 'Transition footwork ladder and net recoveries' },
      { label: 'Main Drill 1', content: 'Crosscourt Lock and Intercept' },
      { label: 'Main Drill 2', content: 'Lob Switch Recovery' },
      { label: 'Serve & Return', content: 'Serve Spot and Poach Window and Return Team Lockout' },
      { label: 'Point Play', content: 'Two Up Closure Wave' },
      { label: 'Competitive Finish', content: 'Doubles Closing Tiebreak' },
      { label: 'Reflection', content: 'Team spacing recap' },
    ],
    coachingEmphasis: 'Connected net movement',
    standards: ['Communication', 'Poach timing', 'Team spacing'],
    commonMistakes: ['Poor backside coverage'],
    matchPlayTransfer: 'Better net and doubles confidence',
  },

  // ═══════════════════════════════════════════════════════════════════
  // FTA UTR 8-10 (Plans 37-40)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-37',
    planNumber: 37,
    name: 'FTA 8-10 Match Identity',
    levelTag: 'FTA UTR 8 to 10',
    level: 'fta',
    subBand: 'UTR 8-10',
    totalTime: 90,
    objective: 'Sharpen clear point identity against strong opposition',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'High pace recovery movement' },
      { label: 'Main Drill 1', content: 'Opponent Type Pattern Block' },
      { label: 'Main Drill 2', content: 'Return Lock and Counter' },
      { label: 'Serve & Return', content: 'FTA Serve Plus Two Sequence and Tiebreak First Serve Pressure' },
      { label: 'Point Play', content: 'Tactical Pattern Points advanced' },
      { label: 'Competitive Finish', content: 'Break Point Down Scenario' },
      { label: 'Reflection', content: 'Tactical adjustment note' },
    ],
    coachingEmphasis: 'Identity under pressure',
    standards: ['Pattern logic', 'Emotional steadiness', 'First strike clarity'],
    commonMistakes: ['Too many pattern changes'],
    matchPlayTransfer: 'Stronger identity versus quality players',
  },
  {
    id: 'sp-38',
    planNumber: 38,
    name: 'FTA 8-10 High Pressure Block',
    levelTag: 'FTA UTR 8 to 10',
    level: 'fta',
    subBand: 'UTR 8-10',
    totalTime: 90,
    objective: 'Perform under realistic scoreboard pressure',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Recover split and defensive reset' },
      { label: 'Main Drill 1', content: 'FTA Scoreboard Decision Game' },
      { label: 'Main Drill 2', content: 'Backhand Line Pressure Release' },
      { label: 'Serve & Return', content: 'Serve Return Tiebreak Starts and Lefty Spin Adaptation' },
      { label: 'Point Play', content: 'Closing Game at 5-4' },
      { label: 'Competitive Finish', content: 'One Changeover Adjustment' },
      { label: 'Reflection', content: 'One pressure choice to keep' },
    ],
    coachingEmphasis: 'Decision making under score',
    standards: ['Routines', 'Smart aggression', 'Problem solving'],
    commonMistakes: ['Overreacting to scoreboard'],
    matchPlayTransfer: 'Better clutch performance',
  },
  {
    id: 'sp-39',
    planNumber: 39,
    name: 'FTA 8-10 Two Hour National Level Day',
    levelTag: 'FTA UTR 8 to 10',
    level: 'fta',
    subBand: 'UTR 8-10',
    totalTime: 120,
    objective: 'Simulate national level training density',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Pace absorb and transition wave footwork' },
      { label: 'Main Drill 1', content: 'Opponent Type Pattern Block' },
      { label: 'Main Drill 2', content: 'Backhand Line Pressure Release' },
      { label: 'Serve & Return', content: 'Return Lock and Counter and Serve Pattern Rehearsal Block' },
      { label: 'Point Play', content: 'Match Pattern Rebuild and FTA Scoreboard Decision Game' },
      { label: 'Competitive Finish', content: 'Match Block Simulation' },
      { label: 'Reflection', content: 'Journaling with tactical adjustment' },
    ],
    coachingEmphasis: 'Professionalism and detail',
    standards: ['High intensity with control', 'Tactical discipline'],
    commonMistakes: ['Trying to make session flashy instead of sharp'],
    matchPlayTransfer: 'Very direct match readiness',
  },
  {
    id: 'sp-40',
    planNumber: 40,
    name: 'FTA 8-10 Advanced Doubles Day',
    levelTag: 'FTA UTR 8 to 10',
    level: 'fta',
    subBand: 'UTR 8-10',
    totalTime: 120,
    objective: 'Sharpen advanced doubles strategy and movement',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and reflex hands' },
      { label: 'Movement', content: 'Poach footwork and cover recovery' },
      { label: 'Main Drill 1', content: 'Australian Return Solve' },
      { label: 'Main Drill 2', content: 'FTA Doubles Poach Window' },
      { label: 'Serve & Return', content: 'I Formation Signal and Go and Server Cover Read' },
      { label: 'Point Play', content: 'Line Cover Decision Game' },
      { label: 'Competitive Finish', content: 'Doubles Closing Tiebreak' },
      { label: 'Reflection', content: 'Team signal review' },
    ],
    coachingEmphasis: 'Smart doubles patterns and trust',
    standards: ['Communication', 'Commitment', 'Clean coverage'],
    commonMistakes: ['Fake advanced doubles without actual structure'],
    matchPlayTransfer: 'Improved advanced doubles execution',
  },

  // ═══════════════════════════════════════════════════════════════════
  // FTA UTR 10-13 (Plans 41-44)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sp-41',
    planNumber: 41,
    name: 'FTA 10-13 Elite Match Prep',
    levelTag: 'FTA UTR 10 to 13',
    level: 'fta',
    subBand: 'UTR 10-13',
    totalTime: 90,
    objective: 'Prepare elite juniors for high level match demands',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Advanced recovery and pace absorb movement' },
      { label: 'Main Drill 1', content: 'Opponent Type Pattern Block' },
      { label: 'Main Drill 2', content: 'Return Lock and Counter' },
      { label: 'Serve & Return', content: 'FTA Serve Plus Two Sequence and Random Target Serve Call' },
      { label: 'Point Play', content: 'FTA Scoreboard Decision Game' },
      { label: 'Competitive Finish', content: 'Break Point Down Scenario' },
      { label: 'Reflection', content: 'One tactical note for competition' },
    ],
    coachingEmphasis: 'Sharp detail with calm execution',
    standards: ['Elite routines', 'Clear tactical purpose', 'No sloppy starts'],
    commonMistakes: ['Overtraining intensity without precision'],
    matchPlayTransfer: 'High level tactical readiness',
  },
  {
    id: 'sp-42',
    planNumber: 42,
    name: 'FTA 10-13 Pressure Closure',
    levelTag: 'FTA UTR 10 to 13',
    level: 'fta',
    subBand: 'UTR 10-13',
    totalTime: 90,
    objective: 'Sharpen closing mentality and pressure identity',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up' },
      { label: 'Movement', content: 'Split recover and transition reset' },
      { label: 'Main Drill 1', content: 'Backhand Line Pressure Release' },
      { label: 'Main Drill 2', content: 'FTA Private Weapon Build adapted to group lane work' },
      { label: 'Serve & Return', content: 'Tiebreak First Serve Pressure and Return Compactness Lock' },
      { label: 'Point Play', content: 'Closing Game at 5-4 and Comeback From 0-3' },
      { label: 'Competitive Finish', content: 'Emotional Discipline Game' },
      { label: 'Reflection', content: 'Pressure journal' },
    ],
    coachingEmphasis: 'Trust your best patterns',
    standards: ['Routines', 'Body language', 'Tactical trust'],
    commonMistakes: ['Hero tennis under score'],
    matchPlayTransfer: 'Better closing and recovery under pressure',
  },
  {
    id: 'sp-43',
    planNumber: 43,
    name: 'FTA 10-13 Full Competition Simulation',
    levelTag: 'FTA UTR 10 to 13',
    level: 'fta',
    subBand: 'UTR 10-13',
    totalTime: 120,
    objective: 'Create the closest practice version of true competition',
    blocks: [
      { label: 'Warm Up', content: 'Full match style warm up' },
      { label: 'Movement', content: 'Live movement activation with reaction feeds' },
      { label: 'Main Drill 1', content: 'Opponent Type Pattern Block' },
      { label: 'Main Drill 2', content: 'FTA Serve Plus Two Sequence' },
      { label: 'Serve & Return', content: 'Lefty Spin Adaptation, Return Lock and Counter, Serve Pattern Rehearsal Block' },
      { label: 'Point Play', content: 'Match Pattern Rebuild and One Changeover Adjustment' },
      { label: 'Competitive Finish', content: 'Match Block Simulation' },
      { label: 'Reflection', content: 'Written match review' },
    ],
    coachingEmphasis: 'Match specific excellence',
    standards: ['Real routines', 'Score awareness', 'Tactical changes'],
    commonMistakes: ['Not treating simulation seriously'],
    matchPlayTransfer: 'Direct elite competition transfer',
  },
  {
    id: 'sp-44',
    planNumber: 44,
    name: 'FTA 10-13 Elite Doubles Preparation',
    levelTag: 'FTA UTR 10 to 13',
    level: 'fta',
    subBand: 'UTR 10-13',
    totalTime: 120,
    objective: 'Prepare elite doubles teams with advanced signals and pressure scenarios',
    blocks: [
      { label: 'Warm Up', content: 'Dynamic warm up and reflex hands' },
      { label: 'Movement', content: 'Poach and switch footwork' },
      { label: 'Main Drill 1', content: 'I Formation Signal and Go' },
      { label: 'Main Drill 2', content: 'FTA Doubles Poach Window' },
      { label: 'Serve & Return', content: 'Australian Return Solve and Server Cover Read' },
      { label: 'Point Play', content: 'Middle Ball Ownership advanced and Line Cover Decision Game' },
      { label: 'Competitive Finish', content: 'Doubles Closing Tiebreak from 5 all' },
      { label: 'Reflection', content: 'Team tactical notes' },
    ],
    coachingEmphasis: 'Trust, precision, and pressure composure',
    standards: ['Clear signals', 'Full commitment', 'Connected spacing'],
    commonMistakes: ['Fancy doubles with poor fundamentals'],
    matchPlayTransfer: 'Elite doubles competition readiness',
  },
];

// Helper: Get unique level groups for filtering
export const sessionPlanLevelGroups = [
  { level: 'prep' as const, subBand: 'Orange Advanced', label: 'Prep Orange', planCount: 4 },
  { level: 'prep' as const, subBand: 'Green Advanced', label: 'Prep Green', planCount: 4 },
  { level: 'jasa' as const, subBand: 'UTR 1-2', label: 'JASA UTR 1-2', planCount: 4 },
  { level: 'jasa' as const, subBand: 'UTR 2-3', label: 'JASA UTR 2-3', planCount: 4 },
  { level: 'asa' as const, subBand: 'UTR 3-5', label: 'ASA UTR 3-5', planCount: 4 },
  { level: 'asa' as const, subBand: 'UTR 5-7', label: 'ASA UTR 5-7', planCount: 4 },
  { level: 'asa' as const, subBand: 'UTR 7-10', label: 'ASA UTR 7-10', planCount: 4 },
  { level: 'fta' as const, subBand: 'UTR 3-5', label: 'FTA UTR 3-5', planCount: 4 },
  { level: 'fta' as const, subBand: 'UTR 5-8', label: 'FTA UTR 5-8', planCount: 4 },
  { level: 'fta' as const, subBand: 'UTR 8-10', label: 'FTA UTR 8-10', planCount: 4 },
  { level: 'fta' as const, subBand: 'UTR 10-13', label: 'FTA UTR 10-13', planCount: 4 },
];
